version: '3.8'

services:
  dxblog_prod:
    build: .
    container_name: dxBlogProdContainer
    image: dxblog_prod
    command: pnpm run start
    volumes:
      - ./dxblog-admin/e2e:/usr/src/app/e2e
    ports:
      - "9090:3000"
    env_file:
      - "./.env.local"
      - "./.env.production"
    depends_on:
      - mongo
    tty: true

  mongo:
    container_name: mongoContainer
    image: mongo
    restart: always
    env_file:
      - "./.env.local"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
    volumes:
      - ./dxblog-admin/mongodb:/data/db
      - ./dxblog-admin/scripts:/docker-entrypoint-initdb.d

  playwright:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./dxblog-admin/playwright-report:/usr/share/nginx/html
