version: '3.8'

services:
  minicrm:
    build: ./.
    container_name: miniCrmContainer
    ports:
      - "9000:3000"
    volumes:
      - ./:/usr/src/app/
    env_file: ./.env
    depends_on:
      - mongo
    tty: true

  mongo:
    container_name: mongoContainer
    image: mongo
    restart: always
    env_file:
      - "./.env"
    volumes:
      - ./mongodb:/data/db
      - ./lib/:/docker-entrypoint-initdb.d

