version: '3.8'

services:
  dxblogadmin:
    build: ./dxblog-admin/.
    container_name: dxBlogAdminContainer
    ports:
      - "9000:3000"
    volumes:
      - ./dxblog-admin:/usr/src/app/
    env_file:
      - "./.env.local"
      - "./.env.development"
    depends_on:
      - mongo
    tty: true

  dxblogsite:
    build: ./dxblog-site/.
    container_name: dxBlogSiteContainer
    command: >
            sh -c
            "
            pnpm install
            && pnpm run dev --host 0.0.0.0 &
            tail -f /dev/null
            "
    ports:
      - "8000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./dxblog-site:/usr/src/site/
    tty: true

  mongo:
    container_name: mongoContainer
    image: mongo
    restart: always
    env_file:
      - "./.env.local"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
    volumes:
      - ./dxblog-admin/mongodb:/data/db
      - ./dxblog-admin/scripts:/docker-entrypoint-initdb.d
