version: '3.8'

services:
  dxblog:
    build: ./.
    container_name: dxBlogContainer
    ports:
      - "9000:3000"
    volumes:
      - ./:/usr/src/app/
    env_file:
      - "./.env.local"
      - "./.env.development"
    depends_on:
      - mongo
    tty: true

  mongo:
    container_name: mongoContainer
    image: mongo
    restart: always
    env_file:
      - "./.env.local"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
    volumes:
      - ./mongodb:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
