version: '3.8'

services:
  minicrm:
    build: ./.
    container_name: miniCrmContainer
    ports:
      - "9000:3000"
    volumes:
      - ./:/usr/src/app/
    env_file: ./.env
    environment:
      - NEXT_PUBLIC_HOST=http://localhost:9000/
    depends_on:
      - mongo
    tty: true

  mongo:
    container_name: mongoContainer
    image: mongo
    restart: always
    env_file:
      - "./.env"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
    volumes:
      - ./mongodb:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
